version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: hpvc_postgres
    restart: always
    environment:
      POSTGRES_USER: hpvc_user
      POSTGRES_PASSWORD: micontraseñasegura123
      POSTGRES_DB: hpvc_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
